# Generated by Django 5.2.8 on 2025-11-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverymodel',
            old_name='customer_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='deliverymodel',
            old_name='firstname_name',
            new_name='username',
        ),
    ]
