# Generated by Django 5.2.8 on 2025-11-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='cart',
            field=models.IntegerField(default=0),
        ),
    ]
