# Generated by Django 5.2.8 on 2025-11-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_productsmodel_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='offer',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='trending',
            field=models.BooleanField(default=0),
        ),
    ]
