# Generated by Django 5.2.8 on 2025-11-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_cartmodel_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
