# Generated by Django 5.2.8 on 2025-11-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cartmodel_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='host',
        ),
    ]
