# Generated by Django 5.2.8 on 2025-12-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_cartmodel_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='product_image',
            field=models.ImageField(default='default.png', upload_to='uploads'),
        ),
    ]
